### ISSUE TITLE
[CES] Weekly Check-ins

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/CES#10]
https://docs.google.com/spreadsheets/d/1C1YvvEo9MUyCuK6pRiuqBLTDJ3SnGfF_uVRHMczrdWc/edit#gid=1565359068

**Comment by garimadosar5** [comment]
**QA Notes** - 
- Questions "Wright" and "BMI", what logic is there. there is no "YES" answer in question 1. Please check.
- BMI is not calculating automatically.
- For "Symptoms Improvement" and "Side effects of Medicine". Check the skip condition. there is no "YES" answer in question 1.
