### ISSUE TITLE
[CES] Treatment Phase End

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/CES#12]
https://docs.google.com/spreadsheets/d/1C1YvvEo9MUyCuK6pRiuqBLTDJ3SnGfF_uVRHMczrdWc/edit#gid=766094504

**Comment by garimadosar5** [comment]
QA Notes - 
- No questions are asked in the visit form.

Did u test it from the Unplanned visit??
Can you explain the flow from where u reached to this visit?
