### ISSUE TITLE
[CES] Visit Scheduling

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/CES#16]
https://docs.google.com/spreadsheets/d/1C1YvvEo9MUyCuK6pRiuqBLTDJ3SnGfF_uVRHMczrdWc/edit#gid=1504022435

Except Visits on Cancel

**Comment by garimadosar5** [comment]
QA Notes - 
- Every time I edit enrolment, it schedules TB screening form. **Fixed**
- After Test result, no visit is getting schedules. (Enrol <- TB Screening <- Screening Sample collection <- Test result for screening <- No visit schedule) **Can you please share the individual name/ visits depends on the test rseults entered.**
- After Lab Test result no visits are getting scheduled. **Please share the test individual**
- On Cancel, no visit is getting scheduled. **On cancel visits are yet to be configured**

**Comment by garimadosar5** [comment]
- After "Test result for Screening" visit, no visit is getting scheduled. **Fixed**
