### ISSUE TITLE
[CES] Line list Report

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/CES#19]
https://docs.google.com/spreadsheets/d/1C1YvvEo9MUyCuK6pRiuqBLTDJ3SnGfF_uVRHMczrdWc/edit#gid=645573136

**Comment by garimadosar5** [comment]
QA Notes - 
- filter start date and end date is not working.
- If I put both the filters, the report gives an error. 
"ERROR: column enl.earliest_visit_date_time does not exist Position: 4828"

**Fixed. The date filters will work for the Program Enrolments during the Start date and End date**
