### ISSUE TITLE
[CES] UAT feedback 15th July

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/CES#21]
https://docs.google.com/spreadsheets/d/1C1YvvEo9MUyCuK6pRiuqBLTDJ3SnGfF_uVRHMczrdWc/edit#gid=155957619

**Comment by garimadosar5** [comment]
QA Notes - 
- Row 58(feedback sheet), Case Amrita Singh - Test Results form did not show TB Status fields after capturing Chest X-ray. 
This is not done.
- Case - Shubham Nagpal. If the form "IP Treatment Phase end" says "IP status" = Completed with extension then it schedules "CP Treatment Phase Start". Check if this is right behaviour.
![IMG_20200809_201949.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/0324a3ed-5938-4fde-9d97-004b8dc2117a)

**Comment by nupoorkhandelwal** [comment]
@garimadosar5  **For point 58**, case Amrita Singh, the test results form did not show the TB status fields. (Initially) Now it is fixed. Pleas check case "**Niraj Tyagi**"

Also, the case **Shubham Nagpal**, is working right now. After IP treatment phase end, CP treatment phase start is scheduled. (IP status can be anything. either IP completed or completed with extension).
