### ISSUE TITLE
[CES][Report] Patients segregated by previous TB History Status (Pie Chart)

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/CES#24]
https://docs.google.com/spreadsheets/d/1ZoOxw1SI3ray28dF4BEO71sz-ixaHHL3g79-OaI3Aog/edit#gid=1177611160&range=22:22

Pie Chart - 
If the patient has a history of TB.

**Comment by garimadosar5** [comment]
QA Notes - 
- This report should show the list of the patient (confirm TB), not enrolled in the program. but this is showing all the enrolled cases because there are 89 cases in this list as well as in report https://reporting.avniproject.org/question/1360.

**Comment by nupoorkhandelwal** [comment]
Added logic - Patients who have been tested as TB positive and has screening done (ie. TB history field data) .

**Comment by nupoorkhandelwal** [comment]
Added logic - Patients who have been tested as TB positive .

https://reporting.openchs.org/question/1411 (with filters)
https://reporting.openchs.org/question/1370

**Comment by garimadosar5** [comment]
QA Notes - 

- By default, the list should show all the non-exit cases but it shoes all the cases.**- NA**
- In Pie chart, filters are not there.
