### ISSUE TITLE
[CES][Report] Patients segregated by where they were referred from (Pie Chart)

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/CES#25]
https://docs.google.com/spreadsheets/d/1ZoOxw1SI3ray28dF4BEO71sz-ixaHHL3g79-OaI3Aog/edit#gid=1177611160&range=33:33

Pie Chart - 
Pie chart on Referral Places

refer the line list from Card #31 and create pie chart on that line list

**Comment by garimadosar5** [comment]
QA Notes - 
- This should be the list of TB patients not enrolled in TB program.

**Why should this be list of individuals who are not enrolled in the program??**

We can discuss this on call.

**Comment by nupoorkhandelwal** [comment]
Created https://reporting.openchs.org/question/1409 (with filters)
https://reporting.openchs.org/question/1379

We can't have filters on reports that are generated on saved questions/line lists. So if we want filtered charts then will have to create a new query for that and then we can have filters on them. 

Also, with graphs having filters dont have option to view the linelist for any selected category.
We should discuss this with Utkarsh.
