### ISSUE TITLE
[CES][Report] Patients segregated by month they were enrolled in

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/CES#26]
https://docs.google.com/spreadsheets/d/1ZoOxw1SI3ray28dF4BEO71sz-ixaHHL3g79-OaI3Aog/edit#gid=1177611160&range=43:43

Bar Chart- 
Bar chart based on the enrolment month.

Use the line list from Card #31 and create a chart on top of that LL.

**Comment by nupoorkhandelwal** [comment]
Created https://reporting.openchs.org/question/1409 (with filters)
https://reporting.openchs.org/question/1379

We can't have filters on reports that are generated on saved questions/line lists. So if we want filtered charts then will have to create a new query for that and then we can have filters on them. 

Also, with graphs having filters dont have option to view the linelist for any selected category.
We should discuss this with Utkarsh.

**Comment by nupoorkhandelwal** [comment]
Created https://reporting.openchs.org/question/1410 (with filters)
https://reporting.openchs.org/question/1390


We can't have filters on reports that are generated on saved questions/line lists. So if we want filtered charts then will have to create a new query for that and then we can have filters on them. 

Also, with graphs having filters dont have option to view the linelist for any selected category.
We should discuss this with Utkarsh.
