### ISSUE TITLE
[CES] Feedback changes

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/CES#33]
https://docs.google.com/spreadsheets/d/1C1YvvEo9MUyCuK6pRiuqBLTDJ3SnGfF_uVRHMczrdWc/edit#gid=155957619&range=71:71

**Comment by garimadosar5** [comment]
QA Notes - 
- Case Mridul Sharma.
No visits got scheduled after "Test Result" for was filled. Please check once.

For TB diagnosis to be positive, either AFB or CNAAT should be positive. This individual have AFB negative and no CBNAAT result to test TB as positive.
