### ISSUE TITLE
[CES] Go Live misc tasks

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/CES#34]
1. Add location datatype on second page of registration for State and District

2. Configure sample unique identifier source in the enrolment.
Its user based identifier. We need to specify the idPrefix in each of the user.
This Id is the first field in enrolment.

3. Upload locations for both catchment and second screen location.
There are three CSV files in the CES folder viz. 1. State and District, 2.Street Locations ,3 Shelter locations

**Comment by arjunk** [comment]
@nupoorkhandelwal @garimadosar5 estimate is missing on this card.

**Comment by nupoorkhandelwal** [comment]
@garima For this card, you will need to take latest of 3.9 client branch. Let me know if u need apk for it.
