### ISSUE TITLE
[CES] Misc changes

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/CES#36]
https://docs.google.com/spreadsheets/d/1oIEaIlMHruX_wzoqcEmiWhr6XF0DxQke/edit#gid=1708071357

Refer to the google sheet for details of specific feedback no. mentioned below.

1. Feedback 3 -  When Smear Microscopy (AFB) Result is not "Smear Negative" it should not ask the user for next visit scheduling. Currently it is asking for all cases. **Made the option AFB negative Followup hide for next visit scheduling when AFB result is not Smear Negative.**

2. Feedback 12 - In TB Diagnosis form, TB Drug type field needs to be non-mandatory or an option  "NA" needs to be added as during initial diagnosis that result may not be available with user. **Done**

3. Feedback 12 - TB Drug type field name can be changed to DR/DS/MDR TB **Done**

4. Test Results - IP Progress form: Why is it asking user to select next visit date after updating CBNAAT Result? (Patient name: Feedback 12 Test) **Fixed**

5. Weekly check ins after the first weekly check in is not being scheduled in IP treatment. this is also resulting in break down of flow due to which other feedback about IP and CP completion cannot be tested. **A rule is failing but its unable to sync due to number of char restriction. It can be fixed after the release**

5. If only FL/SL LPA is selected during sample collection after first week of IP start, test result scheduling of one week should be avoided. **Then when should it get scheduled?**

**Comment by nupoorkhandelwal** [comment]
Moving card on hold since few changes are still not clear. Waiting for a call to confirm them.

**Comment by garimadosar5** [comment]
**QA Notes -** 

- [x] - There are rule failures.
- [x] After TB diagnosis, no visit is getting scheduled. **Case** - ramesh garg

- [x] AFB Negative follow-up, next visit date is given as 07 Jan 21 but it is scheduling the visit for 19 Jan 21. **Case** AFB Negative Followup

- [x] No visit is getting schedule based on the date given in previous encounter.

- [x] In Screening form if FL-LPA and/or SL-LPA is selected then two screening result forms get scheduled. (Test result for LPA and Test result for Screening) but both the forms has same questions.
**Case** - FL/SL LPA
- [x] In case of ongoing treatment case, If CBNAAT result is Rifampicin resistant, then no next visit get scheduled. **Case** - CBNAAT Test

- [x] If Smear microscopy is positive the on next page there is question "Please select next step to be scheduled" and there is nothing as treatment start or anything. **Case** - AFB positive followup

- [x] How to reach to CP/IP treatment forms? Once you start with the Start treatment form, IP/CP will start getting scheduled.

**Comment by utkarshavni** [comment]
Have informed client about the changes on UAT. Waiting for confirmation to move on prod.
