### ISSUE TITLE
[CES]  Test Results Form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/CES#6]
https://docs.google.com/spreadsheets/d/1C1YvvEo9MUyCuK6pRiuqBLTDJ3SnGfF_uVRHMczrdWc/edit#gid=266732857

**Comment by garimadosar5** [comment]
QA Notes - 
-  When "TB result status" question is shown?

**It will be shown after Screening Sample Collections' >>in the Test Results form**
