### ISSUE TITLE
[CES] Treatment Phase Start

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/CES#9]
https://docs.google.com/spreadsheets/d/1C1YvvEo9MUyCuK6pRiuqBLTDJ3SnGfF_uVRHMczrdWc/edit#gid=1074053860

**Comment by garimadosar5** [comment]
QA Notes - 
- "CP start date" is not even in case CP. **Please share the test case /individual**
- In summary, status starts showing CP,  if I fill the unplanned Treatment start phase form. **Treatment phase start is going to be hidden from the Unplanned Visit. Also it will scheduled in the case of CP only**
